version: 2
jobs:
  build:
    working_directory: ~/wdio-cucumber2-framework
    docker:
      - image: circleci/node:4.8.2
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: install-npm
        command: yarn install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - .node_modules
    - run:
        name: test
        command: npm test
    - run:
        name: code-coverage
        command: './node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info'
